### ISSUE TITLE
Using it from Android

### ISSUE THREAD

**Issue by ganeshub** [iron-io/iron_worker_java#23]
This library seem to be working from Android. 
But is it safe to using it from client ?
or library is designed to work only in server environment ?

**Comment by d-kononov** [comment]
Of Course you can use it in Android app.

**Comment by ganeshub** [comment]
Thanks @freeman1988

But I get this warning from library in Android Studio.
I am new to Android development. Is it ok to leave this warning  ?

```
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.4 is ignored for release as it may be conflicting with the internal version provided by Android.
```

**Comment by ganeshub** [comment]
@freeman1988 don't bother, adding this line to build.gradle takes care of the warning

```
configurations {
    compile.exclude group: "org.apache.httpcomponents", module: "httpclient"
}
```
